site_name: CRV Agents
repo_url: https://github.com/aridyckovsky/crv_agents
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - search.suggest
extra_javascript:
  - js/diagrams-nav.js
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            separate_signature: true
            inherited_members: true
            filters: ["!^_"]
            show_if_no_docstring: true
            members_order: source
            group_by_category: true
            show_signature: true
            show_signature_annotations: true
            annotations_path: full
            show_submodules: false
            show_object_full_path: false
            show_root_full_path: false
            line_length: 88
  - gen-files:
      scripts:
        - tools/build_docs.py
  - literate-nav:
      nav_file: SUMMARY.md
