site_name: CRV Agents — Core
repo_url: https://github.com/aridyckovsky/crv_agents
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - search.suggest
extra_javascript:
  - js/diagrams-nav.js
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            separate_signature: true
            preload_modules: [crv.core]
  - gen-files:
      scripts:
        - tools/build_docs.py
  - literate-nav:
      nav_file: SUMMARY.md

nav:
  - Overview: index.md
  - Core:
      - Contracts (README): src/crv/core/README.md
      - Grammar (EBNF): grammar/ebnf.md
      - Grammar diagrams (HTML): grammar/diagrams.html
  - API:
      - crv.core: api/crv_core.md
