site_name: Ascribe Documentation
site_description: Meaning to value to behavior with reproducible CIRVA models
site_author: Ari Dyckovsky
site_url: https://docs.ascribe.live
repo_url: https://github.com/aridyckovsky/ascribe
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - search.suggest

markdown_extensions:
  # Math (Material + MathJax via Arithmatex wrapper)
  - pymdownx.arithmatex:
      generic: true

  # Code blocks (Material recommendations)
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

  # SuperFences (advanced blocks + Mermaid)
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: pymdownx.superfences.fence_code_format
          
extra_javascript:
  # MathJax config must come before the runtime
  - js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

  # Existing site JS
  - js/diagrams-nav.js
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            separate_signature: true
            inherited_members: true
            filters: ["!^_"]
            show_if_no_docstring: true
            members_order: source
            group_by_category: true
            show_signature: true
            show_signature_annotations: true
            annotations_path: full
            show_submodules: false
            show_object_full_path: false
            show_root_full_path: false
            line_length: 88
  - gen-files:
      scripts:
        - tools/build_docs.py
  - literate-nav:
      nav_file: SUMMARY.md
