name: Docs

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCS_USE_DSPY: "true"
      DOCS_DSPY_PROVIDER: "openai"
      DOCS_DSPY_MODEL: "gpt-4o-mini"
      DOCS_BASE_URL: "https://docs.ascribe.live"
      DOCS_DSPY_SEED: "123"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.13

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: tools/ebnf/package-lock.json

      - name: Set cache id (weekly)
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - name: Cache uv, venv and mkdocs caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            ~/.cache
            .venv
          key: ${{ runner.os }}-docs-${{ hashFiles('uv.lock', 'mkdocs.yaml') }}-py3.13-${{ env.cache_id }}
          restore-keys: |
            ${{ runner.os }}-docs-

      - name: Build documentation (DSPy-enabled)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: bash tools/generate_docs.sh build

      - name: Assert llms.txt authored by DSPy
        run: |
          if [ -n "${{ secrets.OPENAI_API_KEY }}" ]; then
            if grep -q '^# llms.txt (fallback)' site/llms.txt; then
              echo "Expected DSPy-authored llms.txt but fallback was emitted."
              exit 1
            else
              echo "DSPy-authored llms.txt verified."
            fi
          else
            echo "No OPENAI_API_KEY secret; skipping DSPy assertion (forks/PRs)."
          fi

      - name: Configure Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v5

      - name: Upload site artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
